
LIST_SYMBOLS = [
    'WLDUSDT', 'RUNEUSDT', 'ETHFIUSDT', 'JASMYUSDT', 'EURIUSDT', 'OMUSDT', 'ARBUSDT', 'STXUSDT', 'BONKUSDT',
    'ENAUSDT', 'QUICKUSDT', 'DOGEUSDT', 'MKRUSDT', 'USDCUSDT', 'BTCUSDC', 'IDEXUSDT', 'DOTUSDT', 'TONUSDT',
    'APTUSDT', 'NEARUSDT', 'PEOPLEUSDT', 'EOSUSDT', 'SOLBTC', 'ARUSDT', 'BTCUSDT', 'WBTCBTC', 'BANANAUSDT',
    'ARKMUSDT', 'EURUSDT', 'ICPUSDT', 'AAVEUSDT', 'SOLUSDC', 'LTCUSDT', 'APEUSDT', 'BOMEUSDT', 'ETHUSDT',
    'SLFUSDT', 'FLOKIUSDT', 'GMTUSDT', 'RENDERUSDT', 'INJUSDT', 'FDUSDUSDT', 'BBUSDT', 'SOLUSDT', 'WIFUSDT',
    'DARUSDT', 'ETHBTC', 'TRBUSDT', 'BCHUSDT', 'NOTUSDT', 'BNXUSDT', 'SHIBUSDT', 'HARDUSDT', 'ETCUSDT',
    'RAREUSDT', 'BNBUSDT', 'VIDTUSDT', 'JUPUSDT', 'XRPUSDT', 'JTOUSDT', 'PEPEUSDT', 'OPUSDT', 'IOUSDT',
    'STMXUSDT', 'FLUXUSDT', 'FILUSDT', 'LDOUSDT', 'GALAUSDT', 'ASTRUSDT', 'STRKUSDT', 'TIAUSDT', 'MATICUSDT',
    'VICUSDT', 'DOGSUSDT', 'FTMUSDT', 'ARBUSDC', 'ATOMUSDT', '1000SATSUSDT', 'ZROUSDT', 'SUNUSDT',
    '1INCHUSDT', 'ETHUSDC', 'SUIUSDT', 'TAOUSDT', 'SEIUSDT', 'PENDLEUSDT', 'LINKUSDT', 'BSWUSDT', 'BNBBTC',
    'SAGAUSDT', 'ZKUSDT', 'TRXUSDT', 'DYDXUSDT', 'ORDIUSDT', 'ADAUSDT', 'FETUSDT', 'UNIUSDT', 'AVAXUSDT',
    'CRVUSDT', 'RDNTUSDT'
]